name: Java CI with Maven + TestNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies (for faster builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build and run tests
      - name: Build & Test with Maven
        run: mvn clean test --file pom.xml

      # Step 5: Upload TestNG Reports
      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestNG-Reports
          path: target/surefire-reports/
